try{
    if(/*myUin.equals("2325459919")||*/myUin.equals("2363768762")){
        String New_Bnben="3.1.4";
        int New_Xiaobanben=314;
        String New_Log=myUin+"是测试用户(勿外传)";
        String New_Download="https://gitee.com/Myn_1/Mao_Yuna/raw/MYN_update/Music/%E7%BE%BD%E9%9B%AB3.1.4.zip";
    }else{
        String New_Bnben="3.1.3";
        int New_Xiaobanben=313;
        String New_Log="V3.1.3---24年12月23日 21:37\n新增报错日志(方便修bug)\n初步适配TIM\n优化解析方法\n优化云更新\n删除桑帛QQ音乐解析";
        String New_Download="https://gitee.com/Myn_1/Mao_Yuna/raw/MYN_update/Music/%E7%BE%BD%E9%9B%AB3.1.3.zip";
    }
}catch(e){
    String New_Bnben="3.1.3";
    int New_Xiaobanben=313;
    String New_Log="V3.1.3---24年12月23日 21:37\n新增报错日志(方便修bug)\n初步适配TIM\n优化解析方法\n优化云更新\n删除桑帛QQ音乐解析";
    String New_Download="https://gitee.com/Myn_1/Mao_Yuna/raw/MYN_update/Music/%E7%BE%BD%E9%9B%AB3.1.3.zip";
}
}
    }
    }
}